export const REDIS_EMAIL_VERIFICATION_KEY = "email-verification";
export const EMAIL_VERIFICATION_CODE_TTL_IN_MIN = 5;
export const EMAIL_VERIFICATION_CODE_TTL_IN_SEC =
  60 * EMAIL_VERIFICATION_CODE_TTL_IN_MIN;
